@startuml

package Diagrama {

class Pokemon {
-id: int
-nombre: String
-etapa: String
-primeraEvolucion: String
-SegundaEvolucion: String
-tipo1: String
-tipo2: String
+Pokemon(id: int,nombre: String,etapa: String,tipo1: String,tipo2: String)
+gets() & sets()
}
Pokemon -down|> PrimeraEvolucion
Pokemon -down|> SegundaEvolucion

class PrimeraEvolucion {
-evolucionBasica: String
-segundaEvolucion: String
+PrimeraEvolucion(id: int,nombre: String,etapa: String,tipo1: String,
tipo2: String,evolucionBasica: String)
+gets() & sets()
}

class SegundaEvolucion {
-evolucionPrevia: String
-evolucionBasica: String
+SegundaEvolucion(id: int,nombre: String,etapa: String,tipo1: String,
tipo2: String,evolucion, evolucionBasica: String, evolucionPrevia: String)
+gets() & sets()
}

class NodoDoble {
-dato: Pokemon
-anterior: NodoDoble
-siguiente: NodoDoble
+NodoDoble (dato: Pokemon)
+gets() & sets()
}
NodoDoble -down>"2" NodoDoble
NodoDoble -down-> Pokemon

class ListaNodoDoble {
-head: NodoDoble
-tail: NodoDoble
+ListaNodoDoble()
+insertarFinalHead(dato: Pokemon): void
+desplegarPokemon(pokemon: Pokemon): void
+deplegarTipo(tipo: String): void
+busquedaPId(id: int): void
+busquedaPNombre(nombre: String): void
+busquedaPersonalizada(pokemon: Pokemon): void
+gets() & sets()
}
ListaNodoDoble o->"2" NodoDoble : Almacena
}

package servicios {

interface Sistema {
+LecturaArchivo(): void
+Menu(): void
+DesplegarPokemonRangoNumero(): void
+DesplegarPokemonOrdenados(): void
+DesplegarTipoPokemon(): void
+DesplegarPrimeraEvolucion(): void
+BusquedaPersonalizada(): void
}

class SistemaImpl {
-listaNodoDoble: ListaNodoDoble
+SistemaImpl()
}
SistemaImpl -|> Sistema
SistemaImpl --> ListaNodoDoble
}

@enduml